### PR TITLE
arcticdb 4.5.0

### PR DESCRIPTION
**Pull request by G-D-Petrov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by G-D-Petrov** [comment]
@conda-forge-admin, please rerender

**Review by jjerphan — APPROVED** [review]
LGTM given :green_circle: CI checks.

Need not be addressed: a couple of doc changes and comment could be ported from `rc` to `main`, see [the absolute diff between the two branches](https://github.com/conda-forge/arcticdb-feedstock/compare/libevent-2.1.10..main).

**Review by DrNickClarke — APPROVED** [review]
LGTM

**Comment by G-D-Petrov** [comment]
@conda-forge-admin, please rerender

**Comment by G-D-Petrov** [comment]
@conda-forge-admin, please rerender

**Comment by G-D-Petrov** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
