### PR TITLE
[libevent-2.1.10] arcticdb 4.5.0

### PR DESCRIPTION
**Pull request by G-D-Petrov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jjerphan — COMMENTED** [review]
We need to port [the new specification on `rc` to this branch](https://github.com/conda-forge/arcticdb-feedstock/compare/libevent-2.1.10..rc#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2R15-R52).

Do you see how to perform this, @G-D-Petrov? Or shall I do it?

**Comment by G-D-Petrov** [comment]
> We need to port [the new specification on `rc` to this branch](https://github.com/conda-forge/arcticdb-feedstock/compare/libevent-2.1.10..rc#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2R15-R52).
> 
> Do you see how to perform this, @G-D-Petrov? Or shall I do it?

@jjerphan I am not sure you mean exactly, can you please do it?

**Comment by jjerphan** [comment]
Done with 832ead4.

@conda-forge-admin, please rerender

**Review by jjerphan — APPROVED** [review]
LGTM given :green_circle: CI checks.

Need not be addressed: a couple of doc changes and comment could be ported from here `rc` to `libevent-2.1.10`, see [the absolute diff between the two branches](https://github.com/conda-forge/arcticdb-feedstock/compare/libevent-2.1.10..rc).

**Pull request merged**
