### PR TITLE
Pick up some open migrations

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #331 
Closes #344
Closes #361
Closes #363

### CODE REVIEW

**Comment by h-vetinari** [comment]
```
  make[3]: *** No rule to make target '$PREFIX/lib/liblzma.so', needed by 'arcticdb/arcticdb_ext.cpython-39-x86_64-linux-gnu.so'.  Stop.
```

**Review by jjerphan — APPROVED** [review]
LGTM given 🟢 CI checks.

Thank you, @h-vetinari.

**Comment by h-vetinari** [comment]
@conda-forge/arcticdb, PTAL! :)

**Review by jjerphan — APPROVED** [review]
LGTM. Thank you, @h-vetinari.

Happy end of the year.

I am off for the end of it. 🎄❄️🎶🥂

**Pull request merged**
